### ISSUE TITLE
C++20's coroutines

### ISSUE THREAD

**Issue by SSBjY-Dave** [lefticus/cpp_weekly#126]
**Channel**
C++Weekly

**Topics**
- The basics of coroutines
- A basic example for co_yield and co_return
- When to use them instead of std::thread

**Length**
I think this topic deserves a longer video something like 15-20 minutes, something like:
- 5 mins - The basics of coroutines
- 7-10 mins - A basic example for co_yield and co_return
- 3-5 mins - When to use them instead of std::thread

**Comment by lefticus** [comment]
Closing as duplicate of the #78
