### ISSUE TITLE
emplace vs emplace_back vs try_emplace vs emplace_hint

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#16]

**Comment by lefticus** [comment]
Mundane:

construct an object in place

- std::optional::emplace
- std::variant::emplace
- std::any::emplace
- std::expected::emplace

insert a new object in a container, and construct it in place at a given location

- std::vector::emplace
- std::list::emplace
- std::forward_list::emplace

insert a new object at the end of a container, and construct it in place

- std::vector::emplace_back
- std::list::emplace_back
- std::forward_list::emplace_back
- std::deque::emplace_back

insert a new object at at the front of a container, and construct it in place

- std::list::emplace_front
- std::forward_list::emplace_front
- std::deque::emplace_front

insert a new object and construct it in place at the automatically chosen correct location

- std::set::emplace
- std::map::emplace
- std::multimap::emplace
- std::multiset::emplace
- std::unordered_set::emplace
- std::unordered_map::emplace
- std::unordered_multimap::emplace
- std::unordered_multiset::emplace

try to insert a new object in place, if one with that key does not already exist

- try_emplace on all unique containers

Tell the container where the element in the container should be inesrted 

- emplace_hint, try_emplace with hint

benchmark 

https://quick-bench.com/q/I9Wmi2dnRwmCeNo-2aLvP6aUTUw

**Comment by lefticus** [comment]
GCC implementation for reference: https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/stl_map.h

**Comment by lefticus** [comment]
All of the possible places `emplace` is used in the stdlib

**Comment by JohelEGP** [comment]
There's also [_`non-propagating-cache`_`::`_`emplace-deref`_](https://eel.is/c++draft/range.nonprop.cache#1.6).

**Comment by lefticus** [comment]
Coming in episode 396
