### ISSUE TITLE
coroutines in C++20

### ISSUE THREAD

**Issue by micromatrix14** [lefticus/cpp_weekly#171]
**Cᐩᐩ Weekly With Jason Turner**

"C++Weekly"  episode request?

**coroutines**

What topics are important to cover for this episode?

**coroutines introduced in C++20 and the related co-await, co-return and co-yield keywords**

Should this be bite-sized (5-10 minutes) or more long-form (10-20 minutes)?
10-20 minutes or even much more is good for coroutines to be covered.

**Comment by stefanos82** [comment]
Can we expand it to include OS signal handling, whether it's applicable or not via C++'s Concurrency support library?

I don't want to depend on POSIX Thread Library if possible.

**Comment by lefticus** [comment]
To actually cover coroutines from C++20, you need a full or multiple-day class. 

I'm going to close this as a duplicate of #78 #96 and #136

**Comment by pfeatherstone** [comment]
Shame. Coroutines are a game changer and there are very few good resources on how to use them.
