### ISSUE TITLE
What are padding and alignment, and why you might care.

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#173]

**Comment by abeimler** [comment]
While I'm not an expert in this, I feel like I'm still missing some tools...

Saw [Visualize padding with C++ Insights](https://www.youtube.com/watch?v=hBUfBaD9038) and my IDE shows me the size of an `struct`, but I still have no idea how to order my members "the right way" and avoid wasting memory.

* I still have no idea what `__attribute__((packed))` and `__attribute__((aligned(...));` are _(I think there is also `#pragma pack`)_
* I'm pretty sure you just can't "reorder members" without breaking ABI ?
* What is `alignof` and `alignas` ?

**Comment by lefticus** [comment]
I'd say "alignof" and "alignas" are outside of the scope of this video, but I can definitely cover some tools on padding and why it might matter.

https://compiler-explorer.com/z/c8KqcTE3M

probably should mention what packing does

**Comment by lefticus** [comment]
Here's a code sample that I played with: https://compiler-explorer.com/z/fb7ssbsfo

* use -Wpadded to find padding
* don't use -Wpadded all the time!
* it's not possible to "fix" all padding issues
* be aware of how struct/class layout can affect your code, cache
* if you rearrange members, you WILL break your ABI!

**Comment by lefticus** [comment]
Coming in Ep410

**Comment by etiennemlb** [comment]
One should try sorting the type by size (ascendant or descendant). This can be proven optimal if the types are power of two is size.
