### ISSUE TITLE
Not Doing This With Your C++ Library Should Be Illegal!

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#181]
* fuzzing

It throws novel inputs at your code, and tries to see what will happen. Can be used to very quickly find memory errors and vulnerabilities.

 Finding the famous heartbleed bug in OpenSSL is now the go-to example of how fuzz testing can be used: https://blog.hboeck.de/archives/868-How-Heartbleed-couldve-been-found.html

* it's what the hackers use

It's very easy to use:

https://compiler-explorer.com/z/drsMvq1Gh

"But I don't parse user input!" you say? https://compiler-explorer.com/z/shsG7E6cG

Simply put, if you are not fuzz testing your code, someone else is!

**Comment by lefticus** [comment]
# Outline

There is one thing that every C++ project should be doing, but far too few are!

Fuzz Testing, or "Fuzzing" is the practice of feeding random inputs into your API find undefined behavior, and specifically memory or threading issues.

Fuzzers work by generating various strings up random data, and it is up to the programmer to decide how handle this data.

If an attacker is looking to compromise your tool, they are going to use a fuzz tester.

if you do any kind of parsing, this is 100% a requirement to test your product, and it looks like if like this:

If you don't know parse input, then do this:

In either case, if you are not fuzzing your product, someone else is.

Consider: what happens if a library like libpng is found to have a memory error? Nearly never device on the planet is open to compromise now.

This is such a serious matter that products like libpng are being "continuously fuzzed" by systems like oss-fuzz from google https://google.github.io/oss-fuzz/

**Comment by lefticus** [comment]
# Outline

There is one thing that every C++ project should be doing, but far too few are!

Fuzz Testing, or "Fuzzing" is the practice of feeding random inputs into your API find undefined behavior, and specifically memory or threading issues.

Fuzzers work by generating various strings up random data, and it is up to the programmer to decide how handle this data.

If an attacker is looking to compromise your tool, they are going to use a fuzz tester.

if you do any kind of parsing, this is 100% a requirement to test your product, and it looks like if like this:

If you don't know parse input, then do this:

In either case, if you are not fuzzing your product, someone else is. This is such a serious matter that products like libpng are being "continuously fuzzed" by systems like oss-fuzz from google https://google.github.io/oss-fuzz/

Consider: what happens if a library like libpng is found to have a memory error?

**Comment by lefticus** [comment]
Example: https://compiler-explorer.com/z/6EWaG5erq

**Comment by lefticus** [comment]
Example for UBSan / Generic inputs: https://compiler-explorer.com/z/snofqPsW9

**Comment by lefticus** [comment]
Coming in episode 352

**Comment by reedhedges** [comment]
FYI the docs for clang/llvm fuzzer (libFuzzer) are at: https://llvm.org/docs/LibFuzzer.html

**Comment by weichslgartner** [comment]
You can use FuzzedDataProvider to transform the byte stream into C++ objects more easily:
https://compiler-explorer.com/z/v9Pqv5xEh
https://compiler-explorer.com/z/s6dzPsWfK

**Comment by lefticus** [comment]
> You can use FuzzedDataProvider to transform the byte stream into C++ objects more easily: https://compiler-explorer.com/z/v9Pqv5xEh https://compiler-explorer.com/z/s6dzPsWfK
> 
> Howto: https://github.com/google/fuzzing/blob/master/docs/split-inputs.md

Thanks, I had no idea that was a thing.

**Comment by WimLeflere** [comment]
YouTube link to the episode
[C++ Weekly - Ep 352 - Not Doing This Should Be Illegal! (Always Fuzz Your C++!)](https://www.youtube.com/watch?v=Is1MurHeZvg)
