### ISSUE TITLE
thread_local

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#19]

**Comment by lefticus** [comment]
https://compiler-explorer.com/z/doExszzz9

**Comment by LB--** [comment]
It's also interesting to see how it works with the global variable version, where it seemingly reveals additional threads not explicitly created: https://compiler-explorer.com/z/PsKMq8PPM
It seems like the global variable needs to be referenced for it to be included though, commenting out the `std::ignore = l;` line changes the output.

**Comment by fcolecumberri** [comment]
/hj You hate so much `std::endl` you prefiere `'\n' << std::flush` over it.

**Comment by lefticus** [comment]
Coming in Ep445

**Comment by lefticus** [comment]
> /hj You hate so much `std::endl` you prefiere `'\n' << std::flush` over it.

`std::endl` should be deprecated. Virtually no one understands what it does (unless they watch my channel :D )
