### ISSUE TITLE
C++ is 40 Years Old... Is C++ Dying?

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#193]
https://developers.slashdot.org/story/22/11/10/227246/nsa-urges-organizations-to-shift-to-memory-safe-programming-languages?sbsrc=md

**Comment by lefticus** [comment]
https://security.googleblog.com/2022/12/memory-safe-languages-in-android-13.html

https://media.defense.gov/2022/Nov/10/2003112742/-1/-1/0/CSI_SOFTWARE_MEMORY_SAFETY.PDF

https://advocacy.consumerreports.org/wp-content/uploads/2023/01/Memory-Safety-Convening-Report-1-1.pdf

**Comment by lefticus** [comment]
Related article: https://accu.org/journals/overload/30/172/teodorescu/

**Comment by lefticus** [comment]
Script / plan:

- I planned this episode back in August https://twitter.com/lefticus/status/1695446205898412073
- but see that Bryce and Conor beat me to the punch in September https://adspthepodcast.com/2023/10/06/Episode-150.html
- (Bryce argues that the core language has stopped evolving)
- I'm not planning to talk about the evolution of the language, just about the statistics of who currently uses C++ and the current growth of users
- After toying with the idea of "When Will C++ Die?" I decided to stay with my original title, except change it to "C++ is 40 years old... Is C++ Dying?"
- The first problem is that the NSA has told developers to stop using C++ https://developers.slashdot.org/story/22/11/10/227246/nsa-urges-organizations-to-shift-to-memory-safe-programming-languages?sbsrc=md
- And then 2022 was the year of the C++ Successor language: https://accu.org/journals/overload/30/172/teodorescu/
  - https://github.com/hsutter/cppfront
  - https://github.com/carbon-language/carbon-lang
  - https://www.hylo-lang.org/ (formerly "val")
- The year of successor languages has come and gone, so where are we?
- Major Applications known to be at least mostly written in C++
  - adobe suite (see talks by adobe developers at C++ conferences)
  - Microsoft office (see talks by ms developers at C++ conferences)
  - Open/Libre Office suites
  - all major web browsers, namely Chromium, Firefox, https://apps.kde.org/konqueror/, and the new greenfield project Ladybird from the Serenity OS project (almost all browsers today use Chromium for the backend)
  - At this point there's almost no reason to continue - this is most tools that most people use today, but we will
  - All C and C++ compilers are written in C++, which means Rust and Python relies on C++ to work.
  - Tensor flow: https://github.com/tensorflow/tensorflow which powers a lot of the world's machine learning/AI work
  - Your JVM: https://github.com/openjdk/jdk
  - Your JavaScript engine: https://github.com/v8/v8
  - Your game engine (Unreal, Godot, Unity, O3DE, etc)

And more anecdotally I have personally done training with students in the 

 - gaming
 - oil
 - energy modeling
 - simulation
 - physics
 - industrial
 - embedded
 - construction
 - GPS
 - medical
 - automotive
 - airline
 - security
 - big data
 - financial
 - manufacturing
 - audio

all of that represents easily many billions of lines of C++ code deployed around the world.

So, C++ is well entrenched right now. But is it dying?

C++ got its name in 1983. it was first standardized in 1998 and a minor update happened in 2003. A long period of stagnation eventually culminated in C++11 being released. The industry was slow to move to C++11, but now I see companies hungry for the latest standards.

C++14,17,20,23 have all released on schedule, every 3 years, and we expect C++26 to also release on schedule.

https://plrank.com/

According to most metrics, C++ is staying at least flat, and is possibly on an upward trend.

* https://www.tiobe.com/tiobe-index/
* https://tjpalmer.github.io/languish/
* https://octoverse.github.com/2022/top-programming-languages

Bryce argues that no major feature was added to C++23, but Bryce doesn't teach C++. C++23 fundamentally changes EVERY example C++ program we will demonstrate. No version of C++ since C++98 has done this.

```cpp
#include <iostream>

int main() {
  std::cout << "Hello World\n";
}
```

becomes

```cpp
import std;

int main() {
  std::println("Hello World");
}
```

Is C++ Dying? I don't think so. Is it growing like it did in the 2010's? Maybe not. Is the lack of new core language features a problem? It depends a lot on who you ask. Many C++ developers what the language to stay more stagnant.

One part of C++ that is definitely not dying: `constexpr`. With this powerful tool we can guarantee that work is done at compile time, which reduces many of the memory, UB, ODR, linking, and runtime questions we have!

**Comment by dotnwat** [comment]
>At this point there's almost no reason to continue - this is most tools that most people use today, but we will

169 databases https://dbdb.io/browse?programming=cplusplus&q=

**Comment by fcolecumberri** [comment]
No language will live forever. At some point C++ will die. By dying I don't mean stop being a legacy language (a lot of projects will not migrate to other languages, the same way COBOL is legacy and is death) I mean at some point people will no longer start new meaningful projects on C++ and I think that point is already arriving.

How many of the big C/C++ projects out there would be written in C/C++ if those were written today. For example:

- Mozilla created the Gecko engine using C++, however when they started Servo (The engine that was supposed to replace Gecko), they used Rust, and there might have been a very big reason behind that.
- Game engines main language support is not C/C++, Unity uses C#, Godot has GDScript. Even then, there are some work made to support Rust.
- The Linux kernel is already supporting Rust as an option to develop part of the kernel.
- It is not uncommon to find common tools remade in Rust that just run faster.

I am not a Rust fanboy (Actually I don't even know the language), I just see how stuff is moving and it is quite clear that C++ is no longer at it's prime and every day is a day closer to it's death.

**Comment by lefticus** [comment]
https://youtu.be/hxjSpasg3gk
