### ISSUE TITLE
C++20's new `<chrono>` features

### ISSUE THREAD

**Issue by ChrisThrasher** [lefticus/cpp_weekly#208]
**Channel**

C++Weekly

**Topics**

C++20's date features, specifically features like [`std::year_month_day`](https://en.cppreference.com/w/cpp/chrono/year_month_day) and it's unexpected properties like how you can make nonsense dates like February 30th if you add 1 month to January 30th.

There was a CppCon talk on this but I don't believe the YouTube video is up yet.

https://cppcon.digital-medium.co.uk/session/2022/using-stdchrono-calendar-dates-for-finance/

**Length**

5-10 minutes

**Comment by bdeane-intel** [comment]
https://www.meetup.com/north-denver-metro-c-meetup/events/290767376/

**Comment by lefticus** [comment]
I've opted to go for a few high level overview of this topic, combining <format> and <chrono> features from C++20

https://compiler-explorer.com/z/hqfchbq7f

**Comment by lefticus** [comment]
OK, I recorded something, and I think it makes sense. It's a "quick start to `<chrono>` (with C++20!)"

**Comment by ChrisThrasher** [comment]
Can't wait to see it!

**Comment by lefticus** [comment]
> Can't wait to see it!

I'm getting a little bit ahead in anticipation of family travel and conference season... it will come out on 2023-09-18 :)

**Comment by lefticus** [comment]
Coming in Ep397
