### ISSUE TITLE
<format> vs {fmt}

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#21]

**Comment by lefticus** [comment]
Main points:

<format> 

* in your standard library, so available (if your standard library has it already)
* doesn't have `print()` until C++23
* beholden to the C++ standard
* ABI stable

{fmt}

* up to the minute bug fixes
* Probably not ABI stable (if you care)
* Many more functions
* constexpr capable

If you have a package manager, you should probably use {fmt}

**Comment by lefticus** [comment]
https://compiler-explorer.com/z/aWo81raYr

**Comment by lefticus** [comment]
Ep 341

**Comment by trcrsired** [comment]
GCC just added std::format 2 days ago. And std::format is very very slow. Same with fmtlib

https://youtu.be/rvKY96OeDJU?t=412
