### ISSUE TITLE
Simple package management with CPM.cmake 

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#211]
I've been hearing a lot of good things about this lately - time to do an episode about it.

https://github.com/cpm-cmake/CPM.cmake

**Comment by SuperFola** [comment]
It could be interesting to compare it with other CMake based package management systems, like FetchContent, vcpkg and ExternalProject (I may have forgotten a few more).

**Comment by lefticus** [comment]
It's directly built on FetchContent and External project, so I don't think it would make sense to compare it to those. It would be more fair to compare it to vcpkg, hunter, conan, etc.

**Comment by abeimler** [comment]
Personally, I use vcpkg + CPM.
Try to move as much dependencies as possible to vcpkg (or conan or other dependencies manager), but sometimes some vcpkg packages (portfiles?) are just outdated or didn't exist.

So it's much easier to use CPM and load the dependencies from github (similar to header-only libraries).  
You can also use `DOWNLOAD_ONLY` for projects without a `CMakeLists.txt`.
`OPTIONS` also seems great for fine-tuning builds (disable features, tests-, benchmark-, example-builds etc.), [vcpkg features selection](https://vcpkg.readthedocs.io/en/latest/users/selecting-library-features/) seem limited.

_(I think writing you own [ports overlay](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) would be the right way, but didn't had the time to do so)_

**Comment by lefticus** [comment]
Notes on SFML/SDL: https://github.com/cpm-cmake/CPM.cmake/pull/292/files

**Comment by lefticus** [comment]
Coming in 372
