### ISSUE TITLE
C++ vs Compiled Python

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#224]

**Comment by lefticus** [comment]
Ep 366. This clearly already needs a followup.

https://youtu.be/vXahGgWfzcA

**Comment by reedhedges** [comment]
FYI Played around a bit with this if anyone is interested, tried some more cppyy usage variations, clang/gcc/with constexpr/without constexpr: https://github.com/reedhedges/cpp_weekly/blob/master/python/conway_game_of_life/Results_RH.txt
