### ISSUE TITLE
C++23's [[assume]]

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#276]
https://en.cppreference.com/w/cpp/language/attributes/assume

**Comment by lefticus** [comment]
Here's an example https://compiler-explorer.com/z/jMh8fz7nK

**Comment by lefticus** [comment]
Coming in episode 412

**Comment by nandanvasudevan** [comment]
After defining a body for `get_ptr()` I am not able to see any improvement with `[[assume]]`.
Why do you think that is?

https://compiler-explorer.com/z/vPWcoo5o6
