### ISSUE TITLE
Why you should avoid code that needs `std::move`

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#299]

**Comment by lefticus** [comment]
See also:

* https://www.youtube.com/watch?v=-dc5vqt2tgA
* https://www.youtube.com/watch?v=2ouxETt75R4
* https://www.youtube.com/watch?v=ZxWjii99yao
* https://www.youtube.com/watch?v=9mWWNYRHAIQ

**Comment by lefticus** [comment]
Toy example: https://compiler-explorer.com/z/5zqqv9jMT

**Comment by lefticus** [comment]
Coming in Ep 404

**Comment by Dharmesh946** [comment]
Hi,

I found that returning the value of a ternary expression has an unexpected (at least for me) behavior with respect to copy and move:
https://godbolt.org/z/ncebdaWvb

I don't know if this is the right issue to comment and maybe you have already covered this topic (I can't remember).

**Comment by LB--** [comment]
@Dharmesh946 I added a `make_S_no_ternary` version that uses if/else instead and that seems to be fully optimized: https://godbolt.org/z/MsM53dcKc

The difference is how the return value gets to the return statement. In the ternary case there is a branch to decide which of two named values to return, disabling named return value optimization (NRVO). In my added function I used the if/else approach to take advantage of normal return value optimization instead (RVO).

**Comment by Dharmesh946** [comment]
@LB thx but I know that if/else solution would have behaved like that. Which puzzled me was that ternary op seemed not to behave as a rvalue (it triggers copy instead of move)

yet it's specified like that in cppreference :
**If E2 and E3 are lvalues of the same type, then the result is an lvalue of that type**, and is a bit-field if at least one of E2 and E3 is a bit-field.

**Comment by LB--** [comment]
@Dharmesh946 Ah, I think you've run into a problem covered in this talk:
[The C++ rvalue lifetime disaster - Arno Schödl. think cell](https://www.youtube.com/watch?v=Tz5drzXREW0)
[The C++ rvalue Lifetime Disaster - Arno Schoedl - C++ on Sea 2023](https://www.youtube.com/watch?v=9V195P3Tv_8)
