### ISSUE TITLE
C++'s First New Floating Point Types in 40 years!

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#303]
https://en.wikipedia.org/wiki/Half-precision_floating-point_format
https://en.wikipedia.org/wiki/Bfloat16_floating-point_format
https://en.wikipedia.org/wiki/IEEE_754
https://en.cppreference.com/w/cpp/types/floating-point
https://en.cppreference.com/w/cpp/header/stdfloat

https://compiler-explorer.com/z/oasbMxnYh

**Comment by fcolecumberri** [comment]
C++ is the only language people can complain about how it evolves very fast and very slow /hj

**Comment by lefticus** [comment]
Coming in Episode 433
