### ISSUE TITLE
C++26's new placeholder identifier!

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#340]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2169r4.pdf

**Comment by lefticus** [comment]
Coming in Episode 414

**Comment by fcolecumberri** [comment]
I wouldn't be surprised if by the end they end up accepting but changing it as `std::placeholders::anonymous_placeholder::more_even_longer_namespace::_` [/hj](https://toneindicators.carrd.co/#masterlist)

**Comment by JohelEGP** [comment]
The identifier is unqualified.
