### ISSUE TITLE
`mutable` (and why to avoid it)

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#36]

**Comment by lefticus** [comment]
https://isocpp.org/blog/2012/12/you-dont-know-const-and-mutable-herb-sutter

**Comment by lefticus** [comment]
https://eel.is/c++draft/res.on.data.races#3

**Comment by lefticus** [comment]
Good link for example: https://compiler-explorer.com/z/79se63ah9

**Comment by lefticus** [comment]
Coming in Ep439

**Comment by hcsch** [comment]
While the recording of Herb Sutter's talk on Channel 9 doesn't seem to be available officially anymore, the [Internet Archive Wayback Machine](https://web.archive.org) luckily has a snapshot with the video in it: https://web.archive.org/web/20170119232617/https://channel9.msdn.com/posts/C-and-Beyond-2012-Herb-Sutter-You-dont-know-blank-and-blank

(please excuse me if this is not the right place for this link suggestion, I thought here might be a better place than in the YT comments on the episode though)

**Comment by lefticus** [comment]
> (please excuse me if this is not the right place for this link suggestion, I thought here might be a better place than in the YT comments on the episode though)

This is perfect, thank you.
