### ISSUE TITLE
lambdas as state machines

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#374]
Example:

https://compiler-explorer.com/z/vjrhYn9Yx

**Comment by lefticus** [comment]
Updated link: https://compiler-explorer.com/z/6dM54GMd4

**Comment by lefticus** [comment]
Coming in Ep426

**Comment by pozemka** [comment]
Just nitpicking. You can insert minus sign in the middle of the parsed number.
```cpp
int main() {
  auto parser = make_int_parser();
  auto result = parser('3');
  result = parser('-');  // <-
  result = parser('2');
  assert(*result == -32);
  std::print("{}", *result);
}
```

**Comment by lefticus** [comment]
Yeah, considering I've written 2 scripting languages now, I'm actually really bad at parsing!
