### ISSUE TITLE
Stop Using .h

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#382]
* hopefully this no longer matters "soon" with modules?

**Comment by LB--** [comment]
I think modules just started a new file extension war between `.ixx` and `.cppm`

**Comment by fcolecumberri** [comment]
> I think modules just started a new file extension war between `.ixx` and `.cppm`

At least none of both can be confused as a pure C file.

**Comment by lefticus** [comment]
Coming in episode 442
