### ISSUE TITLE
Analyzing (and improving) build times

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#39]

**Comment by lefticus** [comment]
Notes:

* `-ftime-trace`
* Look for:
   * expensive headers that can be moved to PCH
   * template instantiations that can be eliminated
   * function templates to `extern` for your users

We'll explore a quick analysis of ChaiScript

**Comment by JohelEGP** [comment]
There's also what `{fmt}` does with `vformat`.

**Comment by lefticus** [comment]
> There's also what `{fmt}` does with `vformat`.

Unless I'm mistaken, this falls into the category of "detemplatizing" code. Do you have a specific link?

**Comment by JohelEGP** [comment]
https://www.zverovich.net/2017/12/09/improving-compile-times.html seems to be it.

**Comment by lefticus** [comment]
Not too far off from what I expected. I'll reference it in the episode.

**Comment by lefticus** [comment]
Coming in episode 338

**Comment by nandanvasudevan** [comment]
Would this be better?

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/Iybb9wnpF00/0.jpg)](https://www.youtube.com/watch?v=Iybb9wnpF00)

**Comment by lefticus** [comment]
> Would this be better? Instead of just the name of the episode. Or is there another way to map the issue to a video about it? [Source](https://stackoverflow.com/questions/11804820/how-can-i-embed-a-youtube-video-on-github-wiki-pages)
> 

That's good yes, but the problem is that I cannot link the episode back here before it's published, so when I queue the video for publication I'm always going to just put the episode #.

**Comment by nandanvasudevan** [comment]
Would it be helpful to add it post publication? Or edit that comment?

**Comment by thomasdarimont** [comment]
I stumbled across this great episode a few days ago and had to smile, because the Java OpenJDK team in their Hotspot c++ codebase has just the same problem with slow builds, because some headers are included quite often.

Maybe you can take a look at it in an follow-up episode :)

https://mail.openjdk.org/pipermail/hotspot-dev/2022-September/063926.html
