### ISSUE TITLE
stupid constexpr tricks

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#399]
You shouldn't expect this to compile, for several reasons, but it does.

https://compiler-explorer.com/z/sb1648Wrr

```cpp
constexpr auto make_val() {
  return 10;
}

int main()
{
  const auto x = 42;
  const auto y = [](){ return 43; }();

  const auto result = [](){
    return x + y + make_val();
  }();

  static_assert(result == 95);
}
```

**Comment by elbeno** [comment]
See Timur's lightning talks from C++Now 2023:
- (the first one) https://www.youtube.com/watch?v=j3x1sr_bzuQ
- (the followup) https://www.youtube.com/watch?v=DKqIIn5iglc

**Comment by lefticus** [comment]
Coming in episode 443
