### ISSUE TITLE
C++23's `std::forward_like`

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#408]
https://en.cppreference.com/w/cpp/utility/forward_like

(it's useful for deducing this)

**Comment by elbeno** [comment]
:+1: https://wg21.link/P2445 cites the original use case for deducing this as a motivation for `forward_like`: optimal forwarding of a lambda capture, where the closure object needs to know if it's a one-shot callback, or if it may be called again.

**Comment by lefticus** [comment]
Episode code sample: https://compiler-explorer.com/z/hh1x7ne3d

**Comment by lefticus** [comment]
Coming in Ep448
