### ISSUE TITLE
std::apply vs std::invoke

### ISSUE THREAD

**Issue by toRatnesh** [lefticus/cpp_weekly#411]
**Channel**
C++Weekly

**Topics**
What is the difference between std::apply and std::invoke?
Why do we need both?

**Length**
5-10

**Comment by lefticus** [comment]
I like this one, thanks @toRatnesh !

**Comment by lefticus** [comment]
Notes:

* `apply` is for calling a Callable with arguments that have been packed into a tuple.
* `invoke` is for calling a Callable with arguments passed direction to the function.

Here's a sample implementation of both along with use examples.

https://compiler-explorer.com/z/jW11xaYro

**Comment by lefticus** [comment]
Coming in Ep 454
