### ISSUE TITLE
Tool Spotlight: valgrind + gdb

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#414]
https://www.redhat.com/en/blog/valgrind-and-gdb-close-cooperation

**Comment by lefticus** [comment]
I'm running into this issue with Manjaro, which makes this a very difficult episode to record

https://www.reddit.com/r/ManjaroLinux/comments/xfmo3g/valgrind_on_manjaro/

**Comment by lefticus** [comment]
Coming in ep453

**Comment by paulfloyd** [comment]
YouTube's autodelete of comments is really bad.

A couple more things from Sasha

https://youtu.be/1VubqWmloZU?si=vzvNUhqwzXHrBsve
https://developers.redhat.com/articles/2021/11/01/debug-memory-errors-valgrind-and-gdb

And a shout out to Philippe Waroquiers, the Valgrind developer that did most of the work on GDB integration with Valgrind.
