### ISSUE TITLE
Tool Spotlight: mull

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#416]
Mutation testing with mull.

* https://github.com/mull-project/mull
* https://mull.readthedocs.io/en/latest/tutorials/HelloWorld.html

**Comment by lefticus** [comment]
https://cppcast.com/alex-denisov/

**Comment by benthevining** [comment]
I tried this tool out a while ago and had trouble getting it set up to build MacOS universal binaries. Hopefully things have improved since then...

**Comment by lefticus** [comment]
Coming in 455
