### ISSUE TITLE
reference qualified members

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#420]

**Comment by lefticus** [comment]
Code sample: https://compiler-explorer.com/z/jE4EKdYET

**Comment by fcolecumberri** [comment]
> Code sample: https://compiler-explorer.com/z/jE4EKdYET

This code looks (maybe I'm wrong) as a good example for a continuation of “deducing this”

**Comment by lefticus** [comment]
This is coming right before "deducing this"

Coming in Ep447
