### ISSUE TITLE
C++26's std::views::concat

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#424]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2542r8.html

**Comment by lefticus** [comment]
https://compiler-explorer.com/z/3341snPea

**Comment by lefticus** [comment]
Coming in Ep461

**Comment by skjasm** [comment]
The "episode details" link in the Youtube description is wrong, it points to https://github.com/lefticus/cpp_weekly/issues/374 instead of here.

**Comment by lefticus** [comment]
> The "episode details" link in the Youtube description is wrong, it points to #374 instead of here.

Fixed, thank you.
