### ISSUE TITLE
C++26 "Remove [[nodiscard]] from the standard"

### ISSUE THREAD

**Issue by m00se-3** [lefticus/cpp_weekly#428]
A request for the "C++Weekly" Channel. 

I just noticed that [[nodiscard]] has been flagged for removal with no real alternative given.

The paper is: P2422R1

**Topics**
Any idea why they would do this? The paper essentially says "it's too annoying."

Do you know of any plans for the standard to make [[nodiscard]] a default behavior? Or was it just a feature that was only good in theory? 

**Length**

I don't really expect a lengthy discussion from this, I just wanted to hear your perspective since you have been a long-time advocate for this.

**Comment by LB--** [comment]
This is startling. We are using `[[nodiscard]]` in combination with a compiler flag to treat the warning as an error to catch code that does the wrong thing. I do think things should have originally been the other way around, with `[[discardable]]` to annotate the rare cases when a return value can be safely ignored, but it seems too late for that, especially since that approach would require annotating code we don't control or using `std::ignore` in many places.

**Comment by SuperFola** [comment]
The [draft](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2422r1.html) says it is a proposal to remove it from the standard library not the language.

**Comment by fcolecumberri** [comment]
If you go into the `What to do instead` it says: `create a separate document containing recommendations where to put [[nodiscard]] in a standard library implementation`.
I think they just want to give order to the documentation, not a real change.

**Comment by elbeno** [comment]
This was approved in plenary in St Louis: https://github.com/cplusplus/papers/issues/1744 - so `[[nodiscard]]` annotations are officially removed from the C++26 standard.

Yes this change is pretty much entirely about process - the committee was spending too much time hashing out `[[nodiscard]]` annotations for things in the library, so now they don't do that. `[[nodiscard]]` can be ignored by conforming implementations anyway, so it wasn't useful to specify it in the standard. Vendors are still free to use `[[nodiscard]]`. As the paper argued, it's a quality-of-implementation issue that the committee doesn't need to spend time on.

**Comment by m00se-3** [comment]
Hmm, I could have sworn that cppreference said "Standard Spec". I looked again and it says "Standard Library Spec".

Sorry for miss reading the proposal.
