### ISSUE TITLE
We didn't get networking in C++20 (or C++23)! Now what?

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#44]
cpprestsdk
other networking libraries
conan, vcpkg

**Comment by the-moisrex** [comment]
I kinda hoped I would get networking in the STL since my web framework would totally benefit from it, but I did too think that asio was way too complicated and too different than the rest of the STL.

I think at this point someone needs to think about starting a new networking library from scratch with the mindset that it's going to be in the STL; not it :)

Anyone designing such thing must probably consider that someday other transport layer protocols like QUIC might find their way into STL as well.

And also I don't think anything higher than the transport layer of OSI should be considered (not that it's been ever haha) just yet.

**Comment by gelldur** [comment]
POCO - https://github.com/pocoproject/poco

**Comment by jcelerier** [comment]
boost.asio here and I don't see that changing any time soon, even if networking TS was standardized as it did not provide all the features of ASIO such as serial port access, Unix sockets etc, only IP, which is woefully insufficient

**Comment by peppemaser** [comment]
I use asio, but I’d like something a bit simpler…

**Comment by VioletGiraffe** [comment]
I have used Qt for TCP and HTTP(S), and I also have used a simple in-house cross-platform wrapper library for sockets, URL handling and HTTP (without SSL). IMO, any network support layer should be able to handle TCP, UDP, HTTPS with sufficient amount of customization for HTTP. For example, I have encountered a problem with SSL on some Windows machines that I couldn't get to the bottom of, but it could be a problem root CA / chain of trust. It was essential to be able to gracefully ignore SSL errors and establish a technically insecure connection over HTTPS.

**Comment by wmerfalen** [comment]
> POCO - https://github.com/pocoproject/poco

That is very cool

**Comment by warped-rudi** [comment]
> I have used Qt for TCP and HTTP(S), and I also have used a simple in-house cross-platform wrapper library for sockets, URL handling and HTTP (without SSL).

Exactly the same here.

**Comment by bdekoz** [comment]
libtorrent

**Comment by Elercia** [comment]
Uvw is great https://github.com/skypjack/uvw

**Comment by VioletGiraffe** [comment]
> Uvw is great https://github.com/skypjack/uvw

That's interesting! What makes it better than industry-standard libraries like `POCO` or `libcurl`? Or `boost::asio` (I won't pretend I know what `asio` is for, but seems to have similarities with `libuv`).

**Comment by wmerfalen** [comment]
If I ever need to interface to a binary through the web, I usually just use a reverse proxy with nginx and listen locally in my application. Handles 99% of the annoyances that goes with having a server up and running... including the complexities of SSL.

**Comment by jeffhammond** [comment]
Thousands of us will keep on using [MPI](https://www.mpi-forum.org/) for another decade at least.

The networking TS was a huge disappointment for me and I hope C++ takes a very different strategy next time.

**Comment by VioletGiraffe** [comment]
@jeffhammond: I think you completely missed the point, MPI is its own thing and is absolutely out of scope for this discussion of general-purpose networking. Of course people will keep using MPI.

**Comment by 5cript** [comment]
https://github.com/5cript/roar
My own for http(s) and websocket based on boost::beast and curl.

**Comment by jeffhammond** [comment]
> @jeffhammond: I think you completely missed the point, MPI is its own thing and is absolutely out of scope for this discussion of general-purpose networking. Of course people will keep using MPI.

MPI is far more general - and sockets far less general - than you seem willing to admit. In any case, I don't want C++ to pull in MPI, just consider more than sockets. 

Look at libfabric or UCX as examples of alternatives to sockets that are capable of expressing high performance networking patterns across a range of technology.

**Comment by VioletGiraffe** [comment]
@jeffhammond: interesting pointers, thank you! I know MPI but never heard of these two libraries.

On generality: a Turing machine is much more general than an ARM or x86 CPU, or than the C++ abstract machine, but it doesn't mean we should all be programming for the Turing machine.

**Comment by lefticus** [comment]
Coming in Episode 345

**Comment by Omnifarious** [comment]
I'll plug mine. :-)

https://github.com/omnifarious/StrMod

It's kind of odd, it's kind of a co-routine thing without co-routines. The co-routine state is kept in StreamModule objects. It has ropes for managing the data coming in and going out. I wrote it a very long time ago, but I do keep it somewhat up-to-date. I've written a couple of commercial things with it.

**Comment by wmerfalen** [comment]
Would it be worth mentioning something like `epoll` here?

**Comment by lefticus** [comment]
> Would it be worth mentioning something like `epoll` here?

May as well post a link to it!

**Comment by 5cript** [comment]
epoll is just one of the low level ways on linux to wait for IO events. https://man7.org/linux/man-pages/man7/epoll.7.html
There is also the new io_uring, which is potentially better than epoll and can also be enabled as an implementation in boost asio using BOOST_ASIO_HAS_IO_URING

**Comment by kassane** [comment]
It is also worth pointing out that [aedis](https://github.com/mzimbres/aedis)(redis client), restinio, [crowCpp](https://github.com/CrowCpp/Crow) are based on asio.
For Qt restAPI there is also [cutelyst](https://github.com/cutelyst/cutelyst).

**Comment by LegalizeAdulthood** [comment]
I've done detailed presentations on POCO, restbed, pistache, Cap'nProto and ZeroMQ for [Utah C++ Programmers](https://www.youtube.com/@UtahCppProgrammers) on our [Network Programming playlist](https://www.youtube.com/playlist?list=PLJDO7P5jAoXzQvuy7UjFoDSdSy_FLqfOf).
