### ISSUE TITLE
[Repeated, please ignore] C++17 std::pmr how and why with expeirence of these years.

### ISSUE THREAD

**Issue by YagaoDirac** [lefticus/cpp_weekly#73]
**Channel**
"C++Weekly"

**Topics**
How to use std::pmr. Some basis is enough. (I just found it in this repo. Sorry for repeating this. I didn't know how to look up.) 
If we really have something new, it would be a potential video.

**Length**
-

**Comment by lefticus** [comment]
I'll close this as a duplicate of the PMR video series I did. 

https://www.youtube.com/playlist?list=PLs3KjaCtOwSYX3X0L36NgwK0pxZZavDSF

See also plans for #47
