### ISSUE TITLE
C++23's `unreachable()`

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#81]
https://en.cppreference.com/w/cpp/utility/unreachable

**Comment by reedhedges** [comment]
And how does it compare to things we might be currently using like `assert(false);`, `abort()`, `exit()`, etc.

**Comment by lefticus** [comment]
https://compiler-explorer.com/z/13Y87Y3ev

**Comment by reedhedges** [comment]
Thanks, played around with that a bit.  One thing to be aware of is that std::unreachable() really needs to be unreachable.  If you make some mistake then you get fun ub:
https://compiler-explorer.com/z/odahGYnTe

**Comment by lefticus** [comment]
> Thanks, played around with that a bit. One thing to be aware of is that std::unreachable() really needs to be unreachable I think?. If you make some mistake and it's not then you get fun ub? https://compiler-explorer.com/z/odahGYnTe

It's explicitly defined as invoking UB, in fact. It feels dangerous to me.

**Comment by lefticus** [comment]
Coming in episode 393
