### ISSUE TITLE
What C++ Needs Next

### ISSUE THREAD

**Issue by fcolecumberri** [lefticus/cpp_weekly#95]
Idea inspired on https://www.youtube.com/watch?v=cWSh4ZxAr7E

**Comment by lefticus** [comment]
So, *my* personal wish list for things I want to see in the language?

**Comment by fcolecumberri** [comment]
> So, *my* personal wish list for things I want to see in the language?

Yes: **Jason Turner's C++ wish list.**

**Comment by lefticus** [comment]
* Pattern Matching (without is / as)
* Removing implicit conversions from the standard library
* Adding reflection (mostly for enumerations, and to aid serialization)

**Comment by lefticus** [comment]
Pattern matching: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2688r0.pdf

**Comment by lefticus** [comment]
Coming in Ep377
